CREATE DATABASE worldcup;
\c worldcup;
CREATE table teams();
CREATE table games();

ALTER TABLE teams ADD COLUMN team_id SERIAL PRIMARY KEY;
ALTER TABLE teams ADD COLUMN name VARCHAR(20) NOT NULL UNIQUE;

ALTER TABLE games ADD COLUMN game_id SERIAL PRIMARY KEY;
ALTER TABLE games ADD COLUMN year INT NOT NULL;
ALTER TABLE games ADD COLUMN round VARCHAR NOT NULL; 

ALTER TABLE games ADD COLUMN winner_id INT NOT NULL REFERENCES teams(team_id);
ALTER TABLE games ADD COLUMN opponent_id INT NOT NULL REFERENCES teams(team_id);

ALTER TABLE games ADD COLUMN winner_goals INT NOT NULL;
ALTER TABLE games ADD COLUMN opponent_goals INT NOT NULL;

